### ISSUE TITLE
로그인 컴포넌트 개선

### ISSUE THREAD

**Issue by gim-hangil** [osamhack2022/WEB_LISTEN_LISTEN#23]
토큰을 쿠키나 스토리지에 저장하니까 토큰이 업데이트가 되어도 컴포넌트를 리렌더링하기 어렵습니다. 그래서 로그인 컴포넌트에서 알아서 로그인했는지의 상태를 관리하도록 해두긴 했는데 굉장히 난잡하네요... 피곤해서 머리가 안 돌아가서 내일 생각해보려고 일단 이슈 올려둡니다.

**Comment by gim-hangil** [comment]
참고로 로그인 컴포넌트가 화면을 덮게 해서 가리는 걸로 했어요. 이것도 당연히 굉장히 이상한 접근인데, 일단은 이렇게 해두었습니다.

**Comment by gim-hangil** [comment]
아 결국 스토리지의 변화를 리액트가 감지하지 못하는 것이 문제니까 스토리지의 데이터를 쓰는 컴포넌트에다가 이벤트 리스터를 달고, 로그인이니 로그아웃을 담당하는 컴포넌트가 이벤트를 발생시키게 하면 되겠네요

**Comment by DHkimgit** [comment]
react-router 사용 안하시니 그 방법이 제가 생각하기엔 가장 편한 방법인 것 같습니다.
